### PR TITLE
Update documentation on using redis-connection with env2

### PR DESCRIPTION
**Pull request by SimonLab**
update the documentation and update the tests to use the REDIS_URL environment variable instead of the REDISCLOUD_URL name see [issue 13](https://github.com/dwyl/redis-connection/issues/13)

### CODE REVIEW

**Comment by SimonLab** [comment]
I think the tests failed on Travis because I use REDIS_URL instead of REDISCLOUD_URL. @nelsonic would it be possible to update the settings on Travis?

**Comment by nelsonic** [comment]
In the interest of supporting *multiple* Redis-as-a-Service providers can we please *keep* `REDISCLOUD_URL` for now and simply have a switch that checks which provider is set?
similar to what we have in the ***esta*** options: 
https://github.com/dwyl/esta/blob/b95fda871d8b690dadba6897c3a79174d5a07f1f/lib/options.js#L27-L28
with corresponding tests for each provider?
https://github.com/dwyl/esta/blob/b95fda871d8b690dadba6897c3a79174d5a07f1f/test/heroku.js

Which provider are you using for your app on Heroku?

**Comment by SimonLab** [comment]
@nelsonic I'm currently using Heroku redis.

**Comment by nelsonic** [comment]
@SimonLab when you have a chance to complete this I think it will be a great addition. 👍

**Comment by nelsonic** [comment]
@SimonLab every so often I come back to this repo and see your _un-recognised work_... if you add me as a contributor on your Fork I can finish it off... 😉

**Comment by nelsonic** [comment]
@SimonLab _other_ people would find this useful... 😉 
If you have time to push your branch to dwyl I will finish it. 🤔

**Comment by nelsonic** [comment]
@SimonLab would be good to get this _merged_ as I said above, this is _useful_ to others. 👍 
if you are able to fix any `merge-conflicts` please do so on "company time". ❤️⏳ 
Thanks! ✨

**Comment by SimonLab** [comment]
@nelsonic sorry for this (small) delay on the PR. Unfortunately I couldn't update my fork with the latest version to resolve the merge conflict. I follow the doc to synchronise a fork: https://help.github.com/articles/syncing-a-fork/ but I couldn't find any "upstream"

 However now that I have the right to create PRs directly (:tada: ) I open a new one: #14 so I guess you can close this one

**Comment by nelsonic** [comment]
@SimonLab please close this PR once the new one is merged 
so the history reflects the desired outcome. 👍 
Thanks! ✨

**Comment by nelsonic** [comment]
Superseded by https://github.com/dwyl/redis-connection/pull/42 fixes #13

**Pull request closed without merging**
