### PR TITLE
Don't create new connections, if connection already present

### PR DESCRIPTION
**Pull request by bboysathish**
Fixes: #17, don't create new connections, if connection already present

### CODE REVIEW

**Comment by nelsonic** [comment]
Hi @bboysathish 
Any idea why Travis is unhappy with the build...? 
I appears the `split(':')`on line 10: https://github.com/bboysathish/redis-connection/blob/a255a52889ea5cdeb834b9b8354a4fd18d00af07/index.js#L10
is causing the fail: https://travis-ci.org/dwyl/redis-connection/builds/92036273#L199
Can you please try changing line 10 of `index.js` to a *conditional assignment*:
```js
auth: redisURL.auth ? redisURL.auth.split(":")[1] : '' // empty string
```

**Comment by bboysathish** [comment]
@nelsonic 

After changing to conditional assignment.

```
d:\E-Learning\myrepo\redis-connection>npm test

> redis-connection@4.0.0 test d:\E-Learning\myrepo\redis-connection
> istanbul cover ./node_modules/tape/bin/tape ./test/*.js


 Error: ENOENT: no such file or directory, open 'd:\E-Learning\myrepo\redis-connection\config.env'
 env2 was required to load a config file but the file was not found. Please see: http://git.io/vG3UZ
TAP version 13
# d:\E-Learning\myrepo\redis-connection\test\local_redis.test.js ->  Connect to LOCAL Redis instance and GET/SET
ok 1 Γ£ô Redis Client connected to: 127.0.0.1:6379
ok 2 Γ£ô LOCAL Redis is LOCAL
# d:\E-Learning\myrepo\redis-connection\test\local_redis.test.js ->  Connect to LOCAL Redis instance and GET/SET
ok 3 Γ£ô Redis Client connected to: 127.0.0.1:6379
ok 4 Γ£ô LOCAL Redis is LOCAL
# Require an existing Redis connection
ok 5 Γ£ô LOCAL Redis is LOCAL
# Require an existing Redis SUBSCRIBER connectiong
ok 6 Γ£ô LOCAL Redis is LOCAL
# Restore REDISCLOUD_URL for Heroku Compatibility tests
ok 7 Γ£ô Connection to LOCAL Closed
# d:\E-Learning\myrepo\redis-connection\test\rediscloud.test.js ->  Confirm RedisCloud is accessible GET/SET
not ok 8 Γ£ô Redis Client connected to: 127.0.0.1:6379
  ---
    operator: ok
    expected: true
    actual:   false
  ...
ok 9 Γ£ô RedisCLOUD is working
ok 10 Γ£ô Connection to RedisCloud Closed
=============================================================================
Writing coverage object [d:\E-Learning\myrepo\redis-connection\coverage\coverage.json]
Writing coverage reports at [d:\E-Learning\myrepo\redis-connection\coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 24/24 )
Branches     : 91.67% ( 11/12 )
Functions    : 100% ( 2/2 )
Lines        : 100% ( 24/24 )
================================================================================

1..10
# tests 10
# pass  9
# fail  1

npm ERR! Test failed.  See above for more details.

```

**Comment by nelsonic** [comment]
Ah... do you have access to a RedisCloud instance?
( *were the tests all passing before the change to the conditional assignment* ? )

**Comment by bboysathish** [comment]
@nelsonic  Nope i don't have access. In local also it was failing. i though the travis may have configured the REDISCLOUD_URL.

**Comment by bboysathish** [comment]
Shall i push conditional operator change. ?

**Comment by nelsonic** [comment]
Hmm... 
Check Gitter. (*I've sent you a valid `REDISCLOUD_URL` ...*)

**Comment by nelsonic** [comment]
Please do push the change to `index.js` with the conditional operator so we can see what Travis-CI says...

**Comment by bboysathish** [comment]
Sure will check and update.

**Comment by bboysathish** [comment]
@nelsonic Once again it fails, but in local it worked like a charm after setting the `REDISCLOUD_URL`. 

See gitter, i have posted the `npm test` result.

**Comment by bboysathish** [comment]
Form what i see in travis log, https://travis-ci.org/dwyl/redis-connection/builds/92070593#L182-L191

`REDISCLOUD_URL` is `undefined`.

**Comment by nelsonic** [comment]
Please try removing the conditional assignment because it should no longer be *required* and will mean that `branch coverage` goes back up to 100%. :+1: 
Thanks! :star:

**Comment by bboysathish** [comment]
@nelsonic i am removing that conditional check, pushing it once again. Thanks.

**Comment by nelsonic** [comment]
Please update the version in `package.json` to `4.0.1` so we can publish this update to NPM. thanks. :+1:

**Comment by bboysathish** [comment]
@nelsonic removing conditional check would fail, if CLOUDURL is undefined. do you want me to remove it. because code coverage is already 100%.

**Comment by nelsonic** [comment]
Technically the `if` on line 5 https://github.com/bboysathish/redis-connection/blob/9829a40771f3c4bb9deb8859871244fabdbf19d4/index.js#L5 should not pass if `REDISCLOUD_URL` is `undefined` which is why there was not a conditional assignment *before*...

**Comment by bboysathish** [comment]
yeah, forgot that. CI is GREEN.

**Comment by nelsonic** [comment]
Try it. it should be fine. :+1:

**Comment by nelsonic** [comment]
Nice one. :star2:

**Comment by nelsonic** [comment]
@SimonLab please try v4.0.1 in the App and thank @bboysathish if #18 is resolved. :+1:

**Comment by SimonLab** [comment]
Thanks @bboysathish and @nelsonic I'll try the new version!

**Pull request merged**
